version: '3'

networks: 
    backend:
    frontend:

services: 
    reverse-proxy:
        build: ./docker-images/nginx-reverse-proxy
        container_name: 'reverse-proxy'
        depends_on: 
            - apache
            - express
        ports: 
            - "8080:80"
        networks: 
            - backend
            - frontend
    apache:
        build: ./docker-images/apache
        container_name: 'apache'
        depends_on: 
            - php-fpm
        networks:
            - backend
            - frontend
        volumes:
            - ./public:/var/www/html
    composer:
        build: ./docker-images/composer
        container_name: 'composer'
        volumes:
            - ./public:/app
    php-fpm:
        build: ./docker-images/php-fpm
        container_name: 'php-fpm'
        depends_on:
            - composer
        networks:
            - backend
        volumes:
            - ./public:/var/www/html
    express:
        build: ./docker-images/express
        container_name: 'express'
        networks:
            - backend
        volumes:
            - ./app:/opt/app
