version: '3'

networks: 
    backend:
    frontend:

services:
    apache:
        build: ./docker-images/apache
        container_name: 'apache'
        ports:
            - "8080:80"
        depends_on:
            - php-fpm
        networks:
            - backend
            - frontend
        volumes:
            - ./public:/var/www/html
    composer:
        build: ./docker-images/composer
        container_name: 'composer'
        volumes:
            - ./public:/app
    php-fpm:
        build: ./docker-images/php-fpm
        container_name: 'php-fpm'
        ports:
            - "9000:9000"
        depends_on:
            - composer
        networks:
            - backend
        volumes:
            - ./public:/var/www/html
    express:
        build: ./docker-images/express
        container_name: 'express'
        ports: 
            - "3000:3000"
        networks: 
            - backend
        volumes: 
            - ./public/js:/opt/app 